name: 'GCP PubSub Github Action'
branding:
  color: blue
  icon: message-square
description: 'Queue GCP PubSub Message from Github Actions'
inputs:
  project-id: 
    description: 'GCP Project ID'
    required: true
  pubsub-topic:
    description: 'PubSub Topic name'
    required: true
  message-body: 
    description: 'PubSub message body'
    required: true
runs:
  using: 'node16'
  main: 'index.js'